# 🏢 Employee Analytics — Capstone Project

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/employees_practice.csv', parse_dates=['hire_date', 'last_promotion_date'])
df.head()

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,bonus,performance_rating,projects_completed,remote_days_per_week,satisfaction_score,training_hours,certifications,is_manager,is_dept_head,last_promotion_date
0,EMP1496,Leo,Miller,leo.miller@company.com,Female,37,Sydney,Australia,HR,PhD,...,16530.00,5,2,4,NaN,14,1,True,False,2023-04-01
1,EMP1787,Quinn,Adams,quinn.adams@company.com,Male,37,Sydney,Australia,Sales,Master,...,4915.40,3,6,0,3.0,70,4,False,False,2019-01-01
2,EMP1087,Quinn,Williams,quinn.williams@company.com,Female,51,Toronto,Canada,Operations,Master,...,5768.55,3,6,0,9.0,36,1,False,False,2022-06-01
3,EMP1726,Yara,Smith,yara.smith@company.com,Male,23,Sydney,Australia,Engineering,Bachelor,...,4450.00,3,7,3,6.0,76,2,False,False,2021-02-01
4,EMP1980,Hank,Phillips,hank.phillips@company.com,Male,60,Toronto,Canada,HR,Master,...,18491.85,5,3,3,1.0,64,1,False,False,2022-04-01

## Part 1 — NumPy Fundamentals

#### 1.1 Basic Statistics

In [2]:
salary_array = df['salary'].dropna().to_numpy()

print("Mean:  ", np.mean(salary_array))
print("Median:", np.median(salary_array))
print("Std:   ", np.std(salary_array))
print("Min:   ", np.min(salary_array))
print("Max:   ", np.max(salary_array))

Mean:   99773.7304964539
Median: 99655.0
Std:    18606.3328742574
Min:    51993.0
Max:    155612.0

#### 1.2 Normalization

In [3]:
normalized_salary_array = (salary_array - salary_array.min())/(salary_array.max() - salary_array.min())

print(normalized_salary_array[:5])  # should be values between 0 and 1, that's what a normalized array means!
print(f"Min: {normalized_salary_array.min()}, Max: {normalized_salary_array.max()}")

[0.56174061 0.44697401 0.61164458 0.35714493 0.68796263]
Min: 0.0, Max: 1.0

#### 1.3 Salary Level Classification

In [4]:
salary_level = np.where(salary_array < 80000, "Low",
               np.where(salary_array <= 110000, "Mid", "High"))
# Or:
'''conditions = [
    salary_array < 80000,
    salary_array <= 110000
]
choices = ["Low", "Mid"]
salary_level = np.select(conditions, choices, default="High")'''
print(salary_level[:10])
print(np.unique(salary_level, return_counts=True))  # shows how many Low/Mid/High

['High' 'Mid' 'High' 'Mid' 'High' 'Mid' 'Mid' 'Mid' 'High' 'High']
(array(['High', 'Low', 'Mid'], dtype='<U4'), array([294, 159, 534]))

#### 1.4 Percentiles

In [5]:
# Calculate percentiles
p25 = np.percentile(salary_array, 25)   # Q1 (25th)
p50 = np.percentile(salary_array, 50)   # Median (50th)  
p75 = np.percentile(salary_array, 75)   # Q3 (75th)
p90 = np.percentile(salary_array, 90)   # 90th

print(f"25th percentile (Q1):  ${p25:,.0f}")
print(f"50th percentile (Median): ${p50:,.0f}")
print(f"75th percentile (Q3):  ${p75:,.0f}")
print(f"90th percentile:       ${p90:,.0f}")

25th percentile (Q1):  $85,694
50th percentile (Median): $99,655
75th percentile (Q3):  $112,882
90th percentile:       $124,015

#### 1.5 2D Array Operations

In [6]:
salary_simulation = np.random.randint(50000, 150001, size= (5, 3)) # simulating 5 employees × 3 months of salary.
mean_salary_per_emp = salary_simulation.mean(axis= 1)
mean_salary_per_mnth = salary_simulation.mean(axis= 0)

print(salary_simulation)
print(f"Mean salary per employee: {mean_salary_per_emp}")
print(f"Mean salary per month: {mean_salary_per_mnth}")

[[121839 142721 110067]
 [135957 134275  80671]
 [117308  90108 110109]
 [130476  86379 147293]
 [136639  93058  75954]]
Mean salary per employee: [124875.66666667 116967.66666667 105841.66666667 121382.66666667
 101883.66666667]
Mean salary per month: [128443.8 109308.2 104818.8]

## Part 2 — Loading & Inspection

#### 2.1 Basic Info

In [7]:
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
df.head()

(1010, 25)
['employee_id', 'first_name', 'last_name', 'email', 'gender', 'age', 'city', 'country', 'department', 'job_education', 'contract_type', 'status', 'hire_date', 'years_experience', 'salary', 'bonus', 'performance_rating', 'projects_completed', 'remote_days_per_week', 'satisfaction_score', 'training_hours', 'certifications', 'is_manager', 'is_dept_head', 'last_promotion_date']
employee_id                        str
first_name                         str
last_name                          str
email                              str
gender                             str
age                              int64
city                               str
country                            str
department                         str
job_education                      str
contract_type                      str
status                             str
hire_date               datetime64[us]
years_experience                 int64
salary                         float64
bonus                          float64
performance_rating               int64
projects_completed               int64
remote_days_per_week             int64
satisfaction_score             float64
training_hours                   int64
certifications                   int64
is_manager                        bool
is_dept_head                      bool
last_promotion_date     datetime64[us]
dtype: object

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,bonus,performance_rating,projects_completed,remote_days_per_week,satisfaction_score,training_hours,certifications,is_manager,is_dept_head,last_promotion_date
0,EMP1496,Leo,Miller,leo.miller@company.com,Female,37,Sydney,Australia,HR,PhD,...,16530.00,5,2,4,NaN,14,1,True,False,2023-04-01
1,EMP1787,Quinn,Adams,quinn.adams@company.com,Male,37,Sydney,Australia,Sales,Master,...,4915.40,3,6,0,3.0,70,4,False,False,2019-01-01
2,EMP1087,Quinn,Williams,quinn.williams@company.com,Female,51,Toronto,Canada,Operations,Master,...,5768.55,3,6,0,9.0,36,1,False,False,2022-06-01
3,EMP1726,Yara,Smith,yara.smith@company.com,Male,23,Sydney,Australia,Engineering,Bachelor,...,4450.00,3,7,3,6.0,76,2,False,False,2021-02-01
4,EMP1980,Hank,Phillips,hank.phillips@company.com,Male,60,Toronto,Canada,HR,Master,...,18491.85,5,3,3,1.0,64,1,False,False,2022-04-01

#### 2.2 Missing Values

In [8]:
# Show the count and percentage of missing values per column. Sort by most missing first:

missing_df = pd.DataFrame({
    'missing_count': df.isnull().sum(),
    'missing_pct': (df.isnull().sum() / len(df)) * 100
})
missing_df['missing_pct'] = missing_df['missing_pct'].round(2)

print(missing_df[missing_df['missing_count'] > 0])

                     missing_count  missing_pct
city                            20         1.98
country                         20         1.98
salary                          23         2.28
satisfaction_score              44         4.36
last_promotion_date             75         7.43

#### 2.3 Unique Values

In [9]:
''' For these columns: gender, department, contract_type, status,job_education,
    city, country — show how many unique values each has and what those values are:'''

cols = ['gender', 'department', 'contract_type', 'status', 
        'job_education', 'city', 'country']
subset = df[cols]

unique_summary = pd.DataFrame({
    'n_unique': subset.nunique(),
    'unique_values': [subset[col].unique() for col in cols]
}, index=cols)

print(unique_summary)

               n_unique                                      unique_values
gender                3                         [Female, Male, Non-binary]
department            7  [HR, Sales, Operations, Engineering, Finance, ...
contract_type         3                   [Part-time, Full-time, Contract]
status                4           [Active, Terminated, Resigned, On Leave]
job_education         4               [PhD, Master, Bachelor, High School]
city                  8  [Sydney, Toronto, Tokyo, Berlin, London, Dubai...
country               8  [Australia, Canada, Japan, Germany, UK, UAE, U...

#### 2.4 Duplicates

In [10]:
# Check if there are any fully duplicate rows. Report how many if any exist:

duplicates_count = df.duplicated().sum()
print(f"Found {duplicates_count} duplicate rows")

# Show the duplicate rows
df[df.duplicated(keep=False)]

Found 10 duplicate rows

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,bonus,performance_rating,projects_completed,remote_days_per_week,satisfaction_score,training_hours,certifications,is_manager,is_dept_head,last_promotion_date
52,EMP1433,Leo,Jackson,leo.jackson@company.com,Female,28,London,UK,Sales,Bachelor,...,12176.25,5,2,3,2.0,74,2,True,False,2022-11-01
77,EMP1259,Ivan,Scott,ivan.scott@company.com,Female,35,London,UK,Engineering,Master,...,5732.05,3,2,4,8.0,68,2,False,False,2020-01-01
175,EMP1295,Carlos,Wright,carlos.wright@company.com,Male,61,Toronto,Canada,HR,Bachelor,...,3961.85,3,5,5,4.0,115,3,True,False,2018-01-01
255,EMP1575,Kevin,Garcia,kevin.garcia@company.com,Female,48,New York,USA,Operations,Bachelor,...,4822.45,3,6,4,5.0,72,3,False,False,2023-07-01
267,EMP1259,Ivan,Scott,ivan.scott@company.com,Female,35,London,UK,Engineering,Master,...,5732.05,3,2,4,8.0,68,2,False,False,2020-01-01
287,EMP1295,Carlos,Wright,carlos.wright@company.com,Male,61,Toronto,Canada,HR,Bachelor,...,3961.85,3,5,5,4.0,115,3,True,False,2018-01-01
325,EMP1969,Julia,Johnson,julia.johnson@company.com,Male,59,Sydney,Australia,Marketing,Master,...,1752.12,2,2,1,10.0,25,2,False,False,2022-04-01
347,EMP1035,Ivy,Hall,ivy.hall@company.com,Male,51,London,UK,Engineering,Master,...,13006.20,4,4,4,6.0,36,2,False,False,2023-10-01
408,EMP1143,Beatrice,Hall,beatrice.hall@company.com,Non-binary,27,Berlin,Germany,Engineering,High School,...,4284.70,3,6,3,1.0,119,3,True,False,2020-09-01
451,EMP1686,Mohamed,Smith,mohamed.smith@company.com,Female,48,Dubai,UAE,Engineering,PhD,...,7249.10,3,5,1,NaN,108,1,True,False,2020-11-01
480,EMP1143,Beatrice,Hall,beatrice.hall@company.com,Non-binary,27,Berlin,Germany,Engineering,High School,...,4284.70,3,6,3,1.0,119,3,True,False,2020-09-01
533,EMP1575,Kevin,Garcia,kevin.garcia@company.com,Female,48,New York,USA,Operations,Bachelor,...,4822.45,3,6,4,5.0,72,3,False,False,2023-07-01
649,EMP1686,Mohamed,Smith,mohamed.smith@company.com,Female,48,Dubai,UAE,Engineering,PhD,...,7249.10,3,5,1,NaN,108,1,True,False,2020-11-01
723,EMP1866,Maya,Anderson,maya.anderson@company.com,Male,24,London,UK,Engineering,Bachelor,...,14742.00,5,5,4,5.0,99,1,False,False,2022-11-01
768,EMP1866,Maya,Anderson,maya.anderson@company.com,Male,24,London,UK,Engineering,Bachelor,...,14742.00,5,5,4,5.0,99,1,False,False,2022-11-01
773,EMP1433,Leo,Jackson,leo.jackson@company.com,Female,28,London,UK,Sales,Bachelor,...,12176.25,5,2,3,2.0,74,2,True,False,2022-11-01
867,EMP1860,Frank,Campbell,frank.campbell@company.com,Female,25,Dubai,UAE,Engineering,Bachelor,...,5030.00,3,9,3,8.0,6,2,False,False,2016-06-01
871,EMP1035,Ivy,Hall,ivy.hall@company.com,Male,51,London,UK,Engineering,Master,...,13006.20,4,4,4,6.0,36,2,False,False,2023-10-01
888,EMP1860,Frank,Campbell,frank.campbell@company.com,Female,25,Dubai,UAE,Engineering,Bachelor,...,5030.00,3,9,3,8.0,6,2,False,False,2016-06-01
983,EMP1969,Julia,Johnson,julia.johnson@company.com,Male,59,Sydney,Australia,Marketing,Master,...,1752.12,2,2,1,10.0,25,2,False,False,2022-04-01

#### 2.5 Date Range

In [11]:
# the earliest and latest hire_date in the dataset?:

earliest_hd = df['hire_date'].min()
latest_hd = df['hire_date'].max()

print(f"the earliest date of hiring is: {earliest_hd} and the latest is {latest_hd}") # min and max works on date too ^^

the earliest date of hiring is: 1990-01-15 00:00:00 and the latest is 2024-12-21 00:00:00

## Part 3 — Data Cleaning

#### 3.1 Column Names

In [12]:
# Standardize all column names: lowercase, strip whitespace, replace spaces with underscores:

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(df.columns)

Index(['employee_id', 'first_name', 'last_name', 'email', 'gender', 'age',
       'city', 'country', 'department', 'job_education', 'contract_type',
       'status', 'hire_date', 'years_experience', 'salary', 'bonus',
       'performance_rating', 'projects_completed', 'remote_days_per_week',
       'satisfaction_score', 'training_hours', 'certifications', 'is_manager',
       'is_dept_head', 'last_promotion_date'],
      dtype='str')

#### 3.2 Smart Salary Fill

In [13]:
# Fill missing salary values with the median salary of that employee's department — not the global median:

df['salary'] = df['salary'].fillna(
    df.groupby('department')['salary'].transform('median')
)

print(df['salary'])

0       110200.0
1        98308.0
2       115371.0
3        89000.0
4       123279.0
          ...
1005    100831.0
1006     97467.0
1007    106501.0
1008     99977.0
1009     70480.0
Name: salary, Length: 1010, dtype: float64

#### 3.3 Satisfaction Score Fill

In [14]:
# Fill missing satisfaction_score with the column mean. Round to 1 decimal:

df['satisfaction_score'] = df['satisfaction_score'].fillna(df['satisfaction_score'].mean().round(1))
print(df['satisfaction_score'])

0       5.3
1       3.0
2       9.0
3       6.0
4       1.0
       ...
1005    9.0
1006    3.0
1007    4.0
1008    5.0
1009    1.0
Name: satisfaction_score, Length: 1010, dtype: float64

#### 3.4 Unknown Location:

In [15]:
# Fill missing city and country with the string "Unknown":

df[['city', 'country']] = df[['city', 'country']].fillna('Unknown')
print(df[['city', 'country']])

          city    country
0       Sydney  Australia
1       Sydney  Australia
2      Toronto     Canada
3       Sydney  Australia
4      Toronto     Canada
...        ...        ...
1005    London         UK
1006  New York        USA
1007    Sydney  Australia
1008    Sydney  Australia
1009     Dubai        UAE

[1010 rows x 2 columns]

#### 3.5 Promotion Date Fill

In [16]:
# Fill missing last_promotion_date with the employee's own hire_date:

df['last_promotion_date'] = df['last_promotion_date'].fillna(df['hire_date'])
print(df['last_promotion_date'])

0      2023-04-01
1      2019-01-01
2      2022-06-01
3      2021-02-01
4      2022-04-01
          ...
1005   2016-02-01
1006   2018-04-01
1007   2015-06-01
1008   2023-01-27
1009   2023-06-26
Name: last_promotion_date, Length: 1010, dtype: datetime64[us]

#### 3.6 Boolean Conversion

In [17]:
# Make sure is_manager and is_dept_head are proper boolean dtype:

if (df['is_dept_head'].dtypes != bool):
    df['is_dept_head'] = df['is_dept_head'].astype(bool)
    print("is_dept_head type successfully set as boolean")
else:
    print("is_dept_head type is already boolean")
    
if (df['is_manager'].dtypes != bool):
    df['is_manager'] = df['is_manager'].map({True: True, False: False, 'True': True, 'False': False}).fillna(False)
    print("is_manager type successfully set as boolean")
else:
    print("is_manager type is already boolean")

is_dept_head type is already boolean
is_manager type is already boolean

#### 3.7 Drop Bad Rows

In [18]:
# Remove rows where both salary AND bonus are missing at the same time:

print(f"Before Removing: \ndf size = {df.size}")

df = df.dropna(subset= ['salary', 'bonus'], how= 'all')

print(f"After Removing: \ndf size = {df.size}")
df.head()

Before Removing:
df size = 25250
After Removing:
df size = 25250

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,bonus,performance_rating,projects_completed,remote_days_per_week,satisfaction_score,training_hours,certifications,is_manager,is_dept_head,last_promotion_date
0,EMP1496,Leo,Miller,leo.miller@company.com,Female,37,Sydney,Australia,HR,PhD,...,16530.00,5,2,4,5.3,14,1,True,False,2023-04-01
1,EMP1787,Quinn,Adams,quinn.adams@company.com,Male,37,Sydney,Australia,Sales,Master,...,4915.40,3,6,0,3.0,70,4,False,False,2019-01-01
2,EMP1087,Quinn,Williams,quinn.williams@company.com,Female,51,Toronto,Canada,Operations,Master,...,5768.55,3,6,0,9.0,36,1,False,False,2022-06-01
3,EMP1726,Yara,Smith,yara.smith@company.com,Male,23,Sydney,Australia,Engineering,Bachelor,...,4450.00,3,7,3,6.0,76,2,False,False,2021-02-01
4,EMP1980,Hank,Phillips,hank.phillips@company.com,Male,60,Toronto,Canada,HR,Master,...,18491.85,5,3,3,1.0,64,1,False,False,2022-04-01

In [19]:
print("Remaining NaNs:")
print(df.isnull().sum()[df.isnull().sum() > 0])
print(f"\nShape after cleaning: {df.shape}")

Remaining NaNs:
Series([], dtype: int64)

Shape after cleaning: (1010, 25)

## Part 4 — Feature Engineering:

#### 4.1 Total Compensation

In [20]:
# Create a total_compensation column = salary + bonus:

total_compensation = df['salary'] + df['bonus']
df['total_compensation'] = df['salary'] + df['bonus']
print(total_compensation)

0       126730.00
1       103223.40
2       121139.55
3        93450.00
4       141770.85
          ...
1005    115955.65
1006    112087.05
1007    118141.00
1008    104975.85
1009     70480.00
Length: 1010, dtype: float64

#### 4.2 Bonus Percentage

In [21]:
# Create bonus_pct = bonus as a percentage of salary. Round to 2 decimals: 

bonus_pct = (df['bonus'] / df['salary']) * 100
bonus_pct = bonus_pct.round(2)
df['bonus_pct'] = (df['bonus'] / df['salary'] * 100).round(2)
print(bonus_pct)

0       15.00
1        5.00
2        5.00
3        5.00
4       15.00
        ...
1005    15.00
1006    15.00
1007    10.93
1008     5.00
1009     0.00
Length: 1010, dtype: float64

#### 4.3 Years Since Promotion

In [22]:
# Create years_since_promotion = number of years between last_promotion_date and today.

years_since_promotion = (pd.Timestamp.now() - df['last_promotion_date']).dt.days
years_since_promotion /= 365.25
df['years_since_promotion'] = years_since_promotion
print(years_since_promotion.round(2))

0        3.00
1        7.25
2        3.83
3        5.16
4        4.00
        ...
1005    10.16
1006     8.00
1007    10.83
1008     3.18
1009     2.77
Name: last_promotion_date, Length: 1010, dtype: float64

#### 4.4 Tenure

In [23]:
# Create tenure_years = how many years the employee has been with the company (from hire_date to today):

tenure_years = (pd.Timestamp.now() - df['hire_date']).dt.days
tenure_years /= 365.25
df['tenure_years'] = tenure_years
print(tenure_years.round(2))

0       17.36
1       17.68
2       31.75
3        4.04
4       36.10
        ...
1005    19.50
1006    21.52
1007    12.04
1008     3.18
1009     2.77
Name: hire_date, Length: 1010, dtype: float64

#### 4.5 Seniority Labels

In [24]:
# Create a seniority column using pd.cut() on tenure_years:

df['seniority'] = pd.cut(tenure_years, 
                         bins=[0, 2, 5, 10, np.inf], 
                         labels=['Junior', 'Mid', 'Senior', 'Lead']) 
print(df['seniority'])

0       Lead
1       Lead
2       Lead
3        Mid
4       Lead
        ...
1005    Lead
1006    Lead
1007    Lead
1008     Mid
1009     Mid
Name: seniority, Length: 1010, dtype: category
Categories (4, str): ['Junior' < 'Mid' < 'Senior' < 'Lead']

#### 4.6 Salary Band

In [25]:
# Create salary_band using pd.qcut() on salary into 4 equal groups labeled Q1, Q2, Q3, Q4:

df['salary_band'] = pd.qcut(df['salary'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
df['salary_band'].value_counts()

salary_band
Q1    253
Q4    253
Q2    252
Q3    252
Name: count, dtype: int64

#### 4.7 Remote Flag

In [26]:
# Create a boolean column is_remote = True if remote_days_per_week >= 3: 

df['is_remote'] = df['remote_days_per_week'] >= 3
print(df['is_remote'])

0        True
1       False
2       False
3        True
4        True
        ...
1005    False
1006    False
1007    False
1008    False
1009     True
Name: is_remote, Length: 1010, dtype: bool

In [27]:
# From hire_date, extract three new columns: hire_year, hire_month, hire_day_of_week (as name e.g. "Monday"):

df['hire_year'] = df['hire_date'].dt.year
df['hire_month'] = df['hire_date'].dt.month
df['hire_day_of_week'] = df['hire_date'].dt.day_name()
print(df[['hire_date', 'hire_year', 'hire_month', 'hire_day_of_week']].head())

   hire_date  hire_year  hire_month hire_day_of_week
0 2008-11-19       2008          11        Wednesday
1 2008-07-26       2008           7         Saturday
2 1994-07-02       1994           7         Saturday
3 2022-03-19       2022           3         Saturday
4 1990-02-23       1990           2           Friday

In [28]:
df = df = df.drop(columns='hire_day_of_week')   
df.head()

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,last_promotion_date,total_compensation,bonus_pct,years_since_promotion,tenure_years,seniority,salary_band,is_remote,hire_year,hire_month
0,EMP1496,Leo,Miller,leo.miller@company.com,Female,37,Sydney,Australia,HR,PhD,...,2023-04-01,126730.00,15.0,3.000684,17.363450,Lead,Q3,True,2008,11
1,EMP1787,Quinn,Adams,quinn.adams@company.com,Male,37,Sydney,Australia,Sales,Master,...,2019-01-01,103223.40,5.0,7.247091,17.681040,Lead,Q2,False,2008,7
2,EMP1087,Quinn,Williams,quinn.williams@company.com,Female,51,Toronto,Canada,Operations,Master,...,2022-06-01,121139.55,5.0,3.832991,31.748118,Lead,Q4,False,1994,7
3,EMP1726,Yara,Smith,yara.smith@company.com,Male,23,Sydney,Australia,Engineering,Bachelor,...,2021-02-01,93450.00,5.0,5.160849,4.035592,Mid,Q2,True,2022,3
4,EMP1980,Hank,Phillips,hank.phillips@company.com,Male,60,Toronto,Canada,HR,Master,...,2022-04-01,141770.85,15.0,4.000000,36.101300,Lead,Q4,True,1990,2

## Part 5 — Filtering & Selection

#### 5.1 Active Engineers

In [29]:
# Select all active, full-time employees in the Engineering department:

active_engineers = df[(df['department'] == 'Engineering') & (df['contract_type'] == 'Full-time') & (df['status'] == 'Active')]
active_engineers.head()

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,last_promotion_date,total_compensation,bonus_pct,years_since_promotion,tenure_years,seniority,salary_band,is_remote,hire_year,hire_month
8,EMP1894,Hank,Young,hank.young@company.com,Male,59,London,UK,Engineering,Master,...,2021-12-01,163139.00,15.0,4.331280,35.348392,Lead,Q4,True,1990,11
9,EMP1384,Alice,Carter,alice.carter@company.com,Male,43,Toronto,Canada,Engineering,Master,...,2020-06-01,117426.75,5.0,5.831622,6.729637,Senior,Q3,True,2019,7
26,EMP1051,Julia,Young,julia.young@company.com,Non-binary,26,London,UK,Engineering,Master,...,2023-01-01,110548.62,2.0,3.247091,6.718686,Senior,Q3,False,2019,7
41,EMP1246,Hank,Adams,hank.adams@company.com,Non-binary,34,Paris,France,Engineering,Bachelor,...,2020-10-01,106044.75,5.0,5.497604,14.866530,Lead,Q3,False,2011,5
45,EMP1987,Rachel,Nelson,rachel.nelson@company.com,Male,47,Sydney,Australia,Engineering,PhD,...,2023-10-01,164609.85,15.0,2.499658,27.854894,Lead,Q4,True,1998,5

#### 5.2 Manager Filter

In [30]:
# Find employees who are managers but NOT department heads, earning more than 100,000

managers_filter = df[(df['is_manager']) & 
                     (~ df['is_dept_head']) &
                     (df['salary'] > 100000)]
managers_filter.head()

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,last_promotion_date,total_compensation,bonus_pct,years_since_promotion,tenure_years,seniority,salary_band,is_remote,hire_year,hire_month
0,EMP1496,Leo,Miller,leo.miller@company.com,Female,37,Sydney,Australia,HR,PhD,...,2023-04-01,126730.00,15.00,3.000684,17.363450,Lead,Q3,True,2008,11
13,EMP1631,Zoe,Phillips,zoe.phillips@company.com,Female,61,Dubai,UAE,Sales,Bachelor,...,2024-12-01,117833.60,15.00,1.330595,29.390828,Lead,Q3,False,1996,11
37,EMP1841,Eve,Moore,eve.moore@company.com,Female,39,Paris,France,Engineering,Bachelor,...,2020-07-01,114535.30,10.00,5.749487,8.361396,Senior,Q3,True,2017,11
46,EMP1548,Sam,Nelson,sam.nelson@company.com,Female,58,Dubai,UAE,Engineering,Bachelor,...,2020-09-01,119218.05,4.98,5.579740,13.664613,Lead,Q4,True,2012,8
56,EMP1799,Nina,Allen,nina.allen@company.com,Female,48,New York,USA,Finance,Bachelor,...,2019-06-01,128358.00,0.00,6.833676,28.438056,Lead,Q4,True,1997,10

#### 5.3 Old Timers

In [31]:
# Find employees hired before 2010 who are still active:

old_timers = df[(df['hire_date'] < '2010-01-01') & (df['status'] == 'Active')]
old_timers.head()

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,last_promotion_date,total_compensation,bonus_pct,years_since_promotion,tenure_years,seniority,salary_band,is_remote,hire_year,hire_month
0,EMP1496,Leo,Miller,leo.miller@company.com,Female,37,Sydney,Australia,HR,PhD,...,2023-04-01,126730.00,15.0,3.000684,17.363450,Lead,Q3,True,2008,11
1,EMP1787,Quinn,Adams,quinn.adams@company.com,Male,37,Sydney,Australia,Sales,Master,...,2019-01-01,103223.40,5.0,7.247091,17.681040,Lead,Q2,False,2008,7
2,EMP1087,Quinn,Williams,quinn.williams@company.com,Female,51,Toronto,Canada,Operations,Master,...,2022-06-01,121139.55,5.0,3.832991,31.748118,Lead,Q4,False,1994,7
8,EMP1894,Hank,Young,hank.young@company.com,Male,59,London,UK,Engineering,Master,...,2021-12-01,163139.00,15.0,4.331280,35.348392,Lead,Q4,True,1990,11
13,EMP1631,Zoe,Phillips,zoe.phillips@company.com,Female,61,Dubai,UAE,Sales,Bachelor,...,2024-12-01,117833.60,15.0,1.330595,29.390828,Lead,Q3,False,1996,11

#### 5.4 Top 10 Earners

In [32]:
# Find the top 10 highest paid employees;
# Show only: first_name, last_name, department, salary:

top_earners = df.sort_values(by='salary', ascending=False).head(10)[['first_name','last_name','department','salary']]
top_earners.head(10)

    first_name last_name   department    salary
655       Tina     Green  Engineering  155612.0
863       Dina     Jones  Engineering  150727.0
964       Lara  Mitchell  Engineering  150352.0
529      Alice     Adams        Legal  150203.0
928    Mohamed   Jackson  Engineering  146900.0
982        Bob   Johnson  Engineering  146671.0
564       Nina  Williams  Engineering  146257.0
451    Mohamed     Smith  Engineering  144982.0
649    Mohamed     Smith  Engineering  144982.0
546       Nina     Adams  Engineering  144309.0

#### 5.5 Unhappy High Performers:

In [33]:
# Find employees with performance_rating of 5 AND satisfaction_score below 5.
# How many are there and what does this pattern suggest?

unhappy_perfo = df[(df['performance_rating']  == 5) & (df['satisfaction_score'] < 5.0)]
print(f"the number of unhappy high performers is: {len(unhappy_perfo)}")
unhappy_perfo.head(10)

the number of unhappy high performers is: 91

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,last_promotion_date,total_compensation,bonus_pct,years_since_promotion,tenure_years,seniority,salary_band,is_remote,hire_year,hire_month
4,EMP1980,Hank,Phillips,hank.phillips@company.com,Male,60,Toronto,Canada,HR,Master,...,2022-04-01,141770.85,15.0,4.000000,36.101300,Lead,Q4,True,1990,2
8,EMP1894,Hank,Young,hank.young@company.com,Male,59,London,UK,Engineering,Master,...,2021-12-01,163139.00,15.0,4.331280,35.348392,Lead,Q4,True,1990,11
13,EMP1631,Zoe,Phillips,zoe.phillips@company.com,Female,61,Dubai,UAE,Sales,Bachelor,...,2024-12-01,117833.60,15.0,1.330595,29.390828,Lead,Q3,False,1996,11
25,EMP1938,Mohamed,Martin,mohamed.martin@company.com,Female,54,New York,USA,Finance,Master,...,2021-06-01,156003.25,15.0,4.832307,32.309377,Lead,Q4,True,1993,12
27,EMP1276,Dina,Thompson,dina.thompson@company.com,Male,44,Sydney,Australia,Finance,Bachelor,...,2024-01-04,105041.00,15.0,2.239562,2.239562,Mid,Q2,False,2024,1
36,EMP1561,Mohamed,Garcia,mohamed.garcia@company.com,Female,50,London,UK,Sales,Bachelor,...,2024-10-01,99095.50,15.0,1.497604,21.464750,Lead,Q2,False,2004,10
38,EMP1226,Ivan,Thomas,ivan.thomas@company.com,Male,57,London,UK,Finance,PhD,...,2017-05-01,152432.50,15.0,8.917180,20.156057,Lead,Q4,True,2006,2
40,EMP1318,Bob,Garcia,bob.garcia@company.com,Male,57,Dubai,UAE,Sales,Bachelor,...,2017-08-01,102521.35,15.0,8.665298,12.624230,Lead,Q2,False,2013,8
45,EMP1987,Rachel,Nelson,rachel.nelson@company.com,Male,47,Sydney,Australia,Engineering,PhD,...,2023-10-01,164609.85,15.0,2.499658,27.854894,Lead,Q4,True,1998,5
52,EMP1433,Leo,Jackson,leo.jackson@company.com,Female,28,London,UK,Sales,Bachelor,...,2022-11-01,93351.25,15.0,3.414100,8.517454,Senior,Q1,True,2017,9

### Analysis: 

High performers (rating=5) are unhappy possibly because:
- They're well paid (Q4) but money alone isn't enough
- They're not being promoted to manager or dept head
- Their contributions are recognized financially but not in title/responsibility
- They are flight risks — best employees who might resign soon

#### 5.6 Query Method

In [34]:
# Use .query() to find all non-binary employees in Sales or Marketing 
# with salary above 85,000:

non_binary = df.query("gender == 'Non-binary' and salary > 85000 and department in ['Marketing','Sales']")
non_binary.head()

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,last_promotion_date,total_compensation,bonus_pct,years_since_promotion,tenure_years,seniority,salary_band,is_remote,hire_year,hire_month
18,EMP1616,Ivan,Mitchell,ivan.mitchell@company.com,Non-binary,34,Paris,France,Sales,Master,...,2022-10-01,101312.4,5.0,3.498973,14.368241,Lead,Q2,False,2011,11
76,EMP1984,Zoe,Thomas,zoe.thomas@company.com,Non-binary,50,London,UK,Sales,Master,...,2023-09-01,96765.9,10.0,2.581793,11.468857,Lead,Q2,True,2014,10
171,EMP1033,Grace,Roberts,grace.roberts@company.com,Non-binary,35,London,UK,Marketing,Bachelor,...,2021-07-01,104397.7,10.0,4.750171,15.764545,Lead,Q2,True,2010,6
554,EMP1221,Beatrice,Garcia,beatrice.garcia@company.com,Non-binary,38,Berlin,Germany,Marketing,Master,...,2015-03-01,108557.7,15.0,11.085558,9.177276,Senior,Q2,False,2017,1
571,EMP1411,Kevin,Mitchell,kevin.mitchell@company.com,Non-binary,37,Paris,France,Marketing,PhD,...,2015-08-01,119890.0,0.0,10.666667,18.239562,Lead,Q4,False,2008,1

## Part 6 — GroupBy & Aggregation

#### 6.1 Department Summary

In [35]:
# For each department compute: headcount, mean salary, max salary, min salary, median bonus.
# Sort by mean salary descending: 

grouped_dept = df.groupby('department').agg(
    headcount=('employee_id', 'count'),
    mean_salary=('salary', 'mean'),
    max_salary=('salary', 'max'),
    min_salary=('salary', 'min'),
    median_bonus=('bonus', 'median')
).sort_values(by='mean_salary', ascending=False)

grouped_dept.head(len(grouped_dept))

             headcount    mean_salary  max_salary  min_salary  median_bonus
department
Legal               50  114552.340000    150203.0     89574.0       9268.05
Engineering        320  113329.709375    155612.0     81931.0       9977.00
Finance            136  106754.647059    138221.0     75227.0      10148.50
Marketing          132   93456.174242    135048.0     63566.0       8777.95
Sales              202   86397.752475    123102.0     59317.0       7445.30
HR                  76   85623.276316    123279.0     52570.0       6510.30
Operations          94   85034.553191    118459.0     51993.0       6716.15

#### 6.2 Status by Country

In [36]:
# For each country; 
# compute the percentage of active vs non-active employees:

country_status = df.groupby('country')['status'].value_counts(normalize=True) * 100
country_status.round(2)
print(country_status)

country    status
Australia  Active        82.644628
           Resigned      14.049587
           Terminated     1.652893
           On Leave       1.652893
Canada     Active        82.882883
           On Leave       6.306306
           Resigned       6.306306
           Terminated     4.504505
France     Active        84.848485
           Resigned       5.303030
           On Leave       5.303030
           Terminated     4.545455
Germany    Active        79.674797
           On Leave       8.130081
           Resigned       6.504065
           Terminated     5.691057
Japan      Active        80.991736
           On Leave       7.438017
           Resigned       7.438017
           Terminated     4.132231
UAE        Active        88.695652
           Resigned       5.217391
           On Leave       3.478261
           Terminated     2.608696
UK         Active        83.076923
           On Leave       6.153846
           Terminated     5.384615
           Resigned       5.384615
USA        Active        82.481752
           On Leave       8.029197
           Resigned       7.299270
           Terminated     2.189781
Unknown    Active        80.000000
           Resigned      10.000000
           On Leave       5.000000
           Terminated     5.000000
Name: proportion, dtype: float64

#### 6.3 Performance by Contract & Seniority

In [37]:
# For each contract_type + seniority combination, compute average performance_rating. 
# Then unstack the result into a readable table:

perfo_by_cont_senio = df.groupby(['contract_type', 'seniority'], observed=False)['performance_rating'].mean().unstack()
print(perfo_by_cont_senio)

seniority        Junior       Mid    Senior      Lead
contract_type
Contract       3.666667  3.850000  3.419355  3.591398
Full-time      2.666667  3.523364  3.745455  3.600467
Part-time      3.500000  3.440000  3.342857  3.706522

#### 6.4 Salary vs Department Average

In [38]:
# Use .transform() to add dept_avg_salary = mean salary of each employee's department.
# Then add salary_vs_dept_avg = difference between employee salary and their dept average:

df['dept_avg_salary'] = df.groupby('department')['salary'].transform('mean')
df['salary_vs_dept_avg'] = df['salary'] - df['dept_avg_salary']

print(df[['first_name', 'department', 'salary', 'dept_avg_salary', 'salary_vs_dept_avg']].head(10))

  first_name   department    salary  dept_avg_salary  salary_vs_dept_avg
0        Leo           HR  110200.0     85623.276316        24576.723684
1      Quinn        Sales   98308.0     86397.752475        11910.247525
2      Quinn   Operations  115371.0     85034.553191        30336.446809
3       Yara  Engineering   89000.0    113329.709375       -24329.709375
4       Hank           HR  123279.0     85623.276316        37655.723684
5        Leo      Finance  100773.0    106754.647059        -5981.647059
6      Frank   Operations   88982.0     85034.553191         3947.446809
7      Diana           HR   84313.0     85623.276316        -1310.276316
8       Hank  Engineering  141860.0    113329.709375        28530.290625
9      Alice  Engineering  111835.0    113329.709375        -1494.709375

#### 6.5 Filter Low Satisfaction Departments

In [39]:
# Keep only employees from departments where the average satisfaction score is above 5: 

filter_employees = df.groupby('department').filter(lambda group: group['satisfaction_score'].mean() > 5)

print(filter_employees.shape)
print("\nDepartments kept:")
print(filter_employees['department'].value_counts())

(1010, 36)

Departments kept:
department
Engineering    320
Sales          202
Finance        136
Marketing      132
Operations      94
HR              76
Legal           50
Name: count, dtype: int64

#### 6.6 Named Aggregations

In [40]:
# Using the modern .agg() named syntax, create a clean department summary with columns: headcount, avg_salary, avg_bonus, avg_performance, avg_satisfaction:

departments_summary = df.groupby('department').agg(
                      headcount=('employee_id', 'count'),
                      avg_salary=('salary', 'mean'),
                      avg_bonus=('bonus', 'mean'),
                      avg_performance=('performance_rating', 'mean'),
                      avg_satisfaction=('satisfaction_score', 'mean')
                      ).round(2)
print(departments_summary)

             headcount  avg_salary  avg_bonus  avg_performance  \
department
Engineering        320   113329.71    9597.79             3.61
Finance            136   106754.65    9275.71             3.68
HR                  76    85623.28    6817.85             3.42
Legal               50   114552.34    9088.79             3.52
Marketing          132    93456.17    8084.12             3.65
Operations          94    85034.55    6771.88             3.53
Sales              202    86397.75    7370.55             3.62

             avg_satisfaction
department
Engineering              5.24
Finance                  5.19
HR                       5.60
Legal                    5.28
Marketing                5.23
Operations               5.32
Sales                    5.42

## Part 7 — Sorting, Ranking & Window Functions

#### 7.1 Salary Rank Within Department

In [41]:
# Rank employees within each department by salary (highest = rank 1). Add as salary_rank_in_dept.

df['salary_rank_in_dept'] = df.groupby('department')['salary'].rank(ascending=False)
print(df[['first_name', 'department', 'salary', 'salary_rank_in_dept']].head(10))

  first_name   department    salary  salary_rank_in_dept
0        Leo           HR  110200.0                  4.0
1      Quinn        Sales   98308.0                 49.0
2      Quinn   Operations  115371.0                  3.0
3       Yara  Engineering   89000.0                312.0
4       Hank           HR  123279.0                  1.0
5        Leo      Finance  100773.0                 93.0
6      Frank   Operations   88982.0                 34.0
7      Diana           HR   84313.0                 34.0
8       Hank  Engineering  141860.0                 12.0
9      Alice  Engineering  111835.0                176.0

#### 7.2 Multi-column Sort

In [42]:
# Sort the DataFrame by department A→Z, then by salary highest first within each department:

sorted_dept = df.sort_values(by= ['department', 'salary'], ascending=[True, False])
sorted_dept.head(10)

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,years_since_promotion,tenure_years,seniority,salary_band,is_remote,hire_year,hire_month,dept_avg_salary,salary_vs_dept_avg,salary_rank_in_dept
655,EMP1488,Tina,Green,tina.green@company.com,Female,59,Paris,France,Engineering,PhD,...,8.161533,32.306639,Lead,Q4,True,1993,12,113329.709375,42282.290625,1.0
863,EMP1362,Dina,Jones,dina.jones@company.com,Female,46,New York,USA,Engineering,PhD,...,11.162218,26.494182,Lead,Q4,True,1999,10,113329.709375,37397.290625,2.0
964,EMP1278,Lara,Mitchell,lara.mitchell@company.com,Non-binary,57,New York,USA,Engineering,Master,...,7.917864,35.723477,Lead,Q4,False,1990,7,113329.709375,37022.290625,3.0
928,EMP1001,Mohamed,Jackson,mohamed.jackson@company.com,Male,57,Sydney,Australia,Engineering,Master,...,4.750171,36.093087,Lead,Q4,True,1990,2,113329.709375,33570.290625,4.0
982,EMP1021,Bob,Johnson,bob.johnson@company.com,Male,60,Paris,France,Engineering,PhD,...,6.833676,35.060917,Lead,Q4,True,1991,3,113329.709375,33341.290625,5.0
564,EMP1891,Nina,Williams,nina.williams@company.com,Male,56,London,UK,Engineering,PhD,...,6.918549,23.915127,Lead,Q4,True,2002,5,113329.709375,32927.290625,6.0
451,EMP1686,Mohamed,Smith,mohamed.smith@company.com,Female,48,Dubai,UAE,Engineering,PhD,...,5.412731,20.454483,Lead,Q4,False,2005,10,113329.709375,31652.290625,7.5
649,EMP1686,Mohamed,Smith,mohamed.smith@company.com,Female,48,Dubai,UAE,Engineering,PhD,...,5.412731,20.454483,Lead,Q4,False,2005,10,113329.709375,31652.290625,7.5
546,EMP1313,Nina,Adams,nina.adams@company.com,Male,58,Toronto,Canada,Engineering,PhD,...,1.664613,31.742642,Lead,Q4,False,1994,7,113329.709375,30979.290625,9.0
544,EMP1319,Ahmed,Jones,ahmed.jones@company.com,Male,50,New York,USA,Engineering,PhD,...,2.414784,21.221081,Lead,Q4,True,2005,1,113329.709375,30078.290625,10.0

#### 7.3 Cumulative Salary Spend

In [43]:
# Sort by hire_date and compute the cumulative total salary as if you hired employees one by one over time:

sorted_hd = df.sort_values(by= 'hire_date') # hd stands for hire_date
sorted_hd['cumulative_salary'] = sorted_hd['salary'].cumsum()
print(sorted_hd[['hire_date', 'first_name', 'salary', 'cumulative_salary']].head(10))

     hire_date first_name    salary  cumulative_salary
364 1990-01-15      Frank   97533.0            97533.0
4   1990-02-23       Hank  123279.0           220812.0
928 1990-02-26    Mohamed  146900.0           367712.0
964 1990-07-11       Lara  150352.0           518064.0
8   1990-11-25       Hank  141860.0           659924.0
915 1991-02-24      Alice   90034.0           749958.0
982 1991-03-10        Bob  146671.0           896629.0
722 1991-06-19      Frank  106795.0          1003424.0
944 1991-07-07        Uma  140393.0          1143817.0
822 1991-07-18    Charlie  111796.0          1255613.0

#### 7.4 Rolling Average

In [44]:
# After sorting by hire_date, compute a 3-employee rolling average of salary. 
# What trend do you notice? 

rolling_averrage = sorted_hd['salary'].rolling(window=3).mean()
print(rolling_averrage)

364              NaN
4                NaN
928    122570.666667
964    140177.000000
8      146370.666667
           ...
146     68540.333333
47      79668.000000
515     84132.000000
117     83527.333333
393     85876.333333
Name: salary, Length: 1010, dtype: float64

### Observation
The 3-employee rolling average is highly volatile because the window 
is too small. No clear trend is visible with window=3.

A larger window (e.g. 30 or 50) would smooth the curve and reveal 
whether salaries increased or decreased over time.

### Optional
Try a **bigger** window to see the trend better:

In [45]:
# For Example: 

sorted_hd['rolling_avg_30'] = sorted_hd['salary'].rolling(window=30).mean()
print(sorted_hd[['hire_date', 'salary', 'rolling_avg_30']].dropna().head(15))

      hire_date    salary  rolling_avg_30
25   1993-12-09  135655.0   121953.200000
655  1993-12-10  155612.0   123889.166667
64   1993-12-20  108204.0   123386.666667
367  1994-01-25  125303.0   122666.766667
720  1994-05-09  115106.0   121491.900000
2    1994-07-02  115371.0   120608.933333
546  1994-07-04  144309.0   122418.100000
980  1994-08-07  119018.0   121496.333333
131  1994-10-25  138097.0   122539.733333
976  1994-11-18  110929.0   121557.600000
302  1994-12-16  132079.0   122233.700000
826  1994-12-24  135856.0   122976.733333
501  1995-02-19  116455.0   122845.233333
638  1995-03-23  110101.0   122420.666667
1000 1995-04-27  139901.0   122905.666667

### Observation
Using a 30-employee rolling average, salaries in the early 1990s 
were consistently high (~$120,000-$123,000). 

This suggests the company's earliest hires were experienced/senior 
employees commanding high salaries. 

A larger dataset would be needed to see if salaries dropped over 
time as the company hired more junior employees.

## Part 8 — String Operations

#### 8.1 Email Domain

In [46]:
# Extract the domain from the email column (everything after @).
# Verify all domains are company.com :

email_domain = df['email'].str.split('@').str[1]
print(email_domain.value_counts())

email
company.com    1010
Name: count, dtype: int64

#### 8.2 Full Name

In [47]:
# Create a full_name column = first_name + " " + last_name: 

df['full_name'] = df['first_name'] + ' ' + df['last_name']
print(df[['first_name', 'last_name', 'full_name']])

     first_name last_name        full_name
0           Leo    Miller       Leo Miller
1         Quinn     Adams      Quinn Adams
2         Quinn  Williams   Quinn Williams
3          Yara     Smith       Yara Smith
4          Hank  Phillips    Hank Phillips
...         ...       ...              ...
1005        Bob  Anderson     Bob Anderson
1006    Mohamed    Martin   Mohamed Martin
1007      Frank     Jones      Frank Jones
1008    Mohamed     Scott    Mohamed Scott
1009   Beatrice    Wright  Beatrice Wright

[1010 rows x 3 columns]

#### 8.3 Standardize Gender

In [48]:
# Make sure all values in the gender column are in Title Case: 

df['gender'] = df['gender'].str.title()
df['gender'].value_counts()

gender
Male          515
Female        453
Non-Binary     42
Name: count, dtype: int64

#### 8.4 Last Name Filter

In [49]:
# Find all employees whose last_name starts with the letter "M":
filter_ln = df['last_name'].str.startswith('M')
filter_ln.value_counts()

last_name
False    896
True     114
Name: count, dtype: int64

#### 8.5 Long First Names

In [50]:
# Count how many employees have a first_name longer than 5 characters:

long_fn = df[df['first_name'].str.len() > 5]
print(f"Employees with first name longer than 5 characters: {len(long_fn)}")

Employees with first name longer than 5 characters: 291

## Part 9 — MultiIndex & Pivot Tables

#### 9.1 Salary Pivot

In [51]:
# Create a pivot table showing average salary by department (rows) and contract_type (columns). 
# Fill missing combinations with 0:

salary_pivot = pd.pivot_table(df, index= 'department', columns='contract_type', values='salary', aggfunc= 'mean', fill_value=0)
print(salary_pivot.round(2))

contract_type   Contract  Full-time  Part-time
department
Engineering    114634.52  113767.48  110173.12
Finance        104608.36  107647.67  103448.69
HR              82331.29   86454.53   84003.64
Legal          115028.29  114866.80  112760.12
Marketing       94986.11   93186.65   93256.05
Operations      87719.80   84791.35   84363.13
Sales           88321.39   86471.07   84389.22

#### 9.2 Headcount Pivot

In [52]:
# Create a pivot table showing headcount by country and gender.
# Add row and column totals: 

headcount_pivot = pd.pivot_table(df, 
                                 index='country', 
                                 columns='gender', 
                                 values='employee_id',
                                 aggfunc='count',
                                 fill_value=0,
                                 margins=True,
                                 margins_name='Total')
headcount_pivot

gender     Female  Male  Non-Binary  Total
country
Australia      54    65           2    121
Canada         53    53           5    111
France         58    65           9    132
Germany        59    58           6    123
Japan          57    58           6    121
UAE            48    64           3    115
UK             63    62           5    130
USA            54    77           6    137
Unknown         7    13           0     20
Total         453   515          42   1010

#### 9.3 MultiIndex Series:

In [53]:
# Group by country + department, compute average salary.
# Then use .xs() to extract just one country's data:

grouped_country = df.groupby(['country', 'department'])['salary'].mean()
Australia_avg = grouped_country.xs('Australia', level='country')
print(Australia_avg.round(2))

department
Engineering    114732.66
Finance        102660.94
HR              82223.42
Legal          125013.00
Marketing       91139.61
Operations      84945.31
Sales           85395.83
Name: salary, dtype: float64

#### 9.4 Cross-tabulation

In [54]:
# Use pd.crosstab() to show the distribution of performance_rating across seniority levels.
# Normalize by row to show percentages:


perfo = pd.crosstab(df['performance_rating'], df['seniority'], normalize='index') * 100
print(perfo.round(2))

seniority           Junior    Mid  Senior   Lead
performance_rating
1                     4.88  17.07   24.39  53.66
2                     2.06  15.46   22.68  59.79
3                     1.39  16.67   21.18  60.76
4                     1.58  13.42   22.63  62.37
5                     0.00  15.20   25.49  59.31

## Part 10 — Combining DataFrames

#### 10.1 Split & Concat

In [55]:
# Split into df_active and df_inactive, then concat() them back.
# Verify the final shape matches the original.

df_active = df[df['status'] == 'Active']
df_inactive = df[df['status'] != 'Active'] 
concat_df = pd.concat([df_active, df_inactive], ignore_index=True)
print(f"the shape is {concat_df.shape}")
concat_df.head(10)

the shape is (1010, 38)

,employee_id,first_name,last_name,email,gender,age,city,country,department,job_education,...,tenure_years,seniority,salary_band,is_remote,hire_year,hire_month,dept_avg_salary,salary_vs_dept_avg,salary_rank_in_dept,full_name
0,EMP1496,Leo,Miller,leo.miller@company.com,Female,37,Sydney,Australia,HR,PhD,...,17.363450,Lead,Q3,True,2008,11,85623.276316,24576.723684,4.0,Leo Miller
1,EMP1787,Quinn,Adams,quinn.adams@company.com,Male,37,Sydney,Australia,Sales,Master,...,17.681040,Lead,Q2,False,2008,7,86397.752475,11910.247525,49.0,Quinn Adams
2,EMP1087,Quinn,Williams,quinn.williams@company.com,Female,51,Toronto,Canada,Operations,Master,...,31.748118,Lead,Q4,False,1994,7,85034.553191,30336.446809,3.0,Quinn Williams
3,EMP1726,Yara,Smith,yara.smith@company.com,Male,23,Sydney,Australia,Engineering,Bachelor,...,4.035592,Mid,Q2,True,2022,3,113329.709375,-24329.709375,312.0,Yara Smith
4,EMP1617,Frank,Campbell,frank.campbell@company.com,Male,34,Tokyo,Japan,Operations,Master,...,14.959617,Lead,Q2,True,2011,4,85034.553191,3947.446809,34.0,Frank Campbell
5,EMP1263,Diana,Adams,diana.adams@company.com,Non-Binary,28,Berlin,Germany,HR,Master,...,8.558522,Senior,Q1,False,2017,9,85623.276316,-1310.276316,34.0,Diana Adams
6,EMP1894,Hank,Young,hank.young@company.com,Male,59,London,UK,Engineering,Master,...,35.348392,Lead,Q4,True,1990,11,113329.709375,28530.290625,12.0,Hank Young
7,EMP1384,Alice,Carter,alice.carter@company.com,Male,43,Toronto,Canada,Engineering,Master,...,6.729637,Senior,Q3,True,2019,7,113329.709375,-1494.709375,176.0,Alice Carter
8,EMP1004,Hank,Allen,hank.allen@company.com,Female,25,Berlin,Germany,Sales,High School,...,5.330595,Senior,Q1,True,2020,12,86397.752475,-15358.752475,177.0,Hank Allen
9,EMP1637,Hana,Jackson,hana.jackson@company.com,Female,36,Toronto,Canada,Sales,Bachelor,...,12.145106,Lead,Q1,True,2014,2,86397.752475,-5644.752475,126.0,Hana Jackson

#### 10.2 Budget Merge

In [56]:
# Create this DataFrame manually:

dept_budget = pd.DataFrame({
    'department': ['Engineering', 'Sales', 'HR', 'Finance',
                   'Marketing', 'Operations', 'Legal'],
    'annual_budget': [68_000_000, 33_000_000, 14_000_000,
                      28_000_000, 24_000_000, 18_000_000, 12_000_000]
})
# Merge it with your main DataFrame. Then compute what percentage of each department's budget goes to total salaries:

merged_dept = df.groupby('department')['salary'].sum().reset_index().merge(dept_budget, on= ['department'])
merged_dept['percentage'] = merged_dept['salary'] * 100 / merged_dept['annual_budget']
merged_dept.head(20)

    department      salary  annual_budget  percentage
0  Engineering  36265507.0       68000000   53.331628
1      Finance  14518632.0       28000000   51.852257
2           HR   6507369.0       14000000   46.481207
3        Legal   5727617.0       12000000   47.730142
4    Marketing  12336215.0       24000000   51.400896
5   Operations   7993248.0       18000000   44.406933
6        Sales  17452346.0       33000000   52.885897

## Part 11 — Final Business Analysis

#### 11.1 Attrition by Department

In [57]:
# Which department has the highest attrition rate? (attrition = Resigned or Terminated)


df['attrited'] = df['status'].isin(['Resigned', 'Terminated'])
print(f"Total attrited employees: {df['attrited'].sum()}")
dept_attrition = (df.groupby('department')
                  .agg({
                      'attrited': 'mean',        # Proportion
                      'employee_id': 'count'     # Headcount
                  })
                  .round(3)
                  .rename(columns={
                      'attrited': 'attrition_rate',
                      'employee_id': 'headcount'
                  })
)
dept_attrition['attrition_rate'] *= 100
dept_attrition = dept_attrition.sort_values('attrition_rate', ascending=False)
print("\nDepartment Attrition Summary:")
print(dept_attrition.head(7))
print(f"\nHighest attrition department: {dept_attrition.index[0]}")

Total attrited employees: 112

Department Attrition Summary:
             attrition_rate  headcount
department
HR                     17.1         76
Operations             12.8         94
Engineering            12.2        320
Marketing              11.4        132
Finance                 9.6        136
Sales                   8.4        202
Legal                   6.0         50

Highest attrition department: HR

#### 11.2 Experience vs Salary

In [58]:
# Is there a correlation between years_experience and salary?

correlation = df['salary'].corr(df['years_experience'])
print(correlation)

0.5488685889438149

### Observation
There's a moderately strong positive relationship between salary and experience years. As one increases, the other tends to increase too, but it's not a perfect relationship!

#### 11.3 Managers vs Non-Managers

In [59]:
# Do managers earn significantly more than non-managers on average? :

managers = df.loc[df['is_manager'], 'salary'].mean()
employees = df.loc[~df['is_manager'], 'salary'].mean()

print(f"Managers:  ${managers:,.0f}")
print(f"Employees: ${employees:,.0f}") 
print(f"Difference:${managers - employees:+,.0f}")

Managers:  $101,443
Employees: $99,234
Difference:$+2,209

#### 11.4 — Education vs Performance

In [60]:


education = df.groupby('job_education')['performance_rating'].mean().sort_values(ascending=False)
print(education)

job_education
High School    3.705882
Bachelor       3.621076
Master         3.567568
PhD            3.543478
Name: performance_rating, dtype: float64

#### 11.5 Promotion Speed

In [61]:
# What is the average time between hire_date and last_promotion_date in years? Which department promotes fastest?:

df['promotion_speed'] = (pd.to_datetime(df['last_promotion_date']) - 
                        pd.to_datetime(df['hire_date'])).dt.days / 365.25

dept_promotion = (df.groupby('department')['promotion_speed']
                  .mean()
                  .sort_values()  
                  .round(1)
)

print("Average years to first promotion by department:")
print(dept_promotion)
print(f"\n FASTEST PROMOTING: {dept_promotion.index[0]} ({dept_promotion.iloc[0]:.1f} years)")

Average years to first promotion by department:
department
Legal          7.6
Finance        7.7
Marketing      8.0
Sales          8.4
HR             9.0
Engineering    9.0
Operations     9.4
Name: promotion_speed, dtype: float64

 FASTEST PROMOTING: Legal (7.6 years)

##### 11.6 CEO Dashboard

In [62]:
# Create a single clean summary DataFrame — one row per department
# containing: headcount, avg_salary, attrition_rate, avg_performance, avg_satisfaction, avg_tenure.
# Export it to ../outputs/dept_summary.csv.

ceo_dashboard = df.groupby('department').agg(
    headcount        = ('employee_id',        'count'),
    avg_salary       = ('salary',             'mean'),
    attrition_rate   = ('attrited',           'mean'),
    avg_performance  = ('performance_rating', 'mean'),
    avg_satisfaction = ('satisfaction_score', 'mean'),
    avg_tenure       = ('tenure_years',       'mean'),
).round(2)

ceo_dashboard['attrition_rate'] = (ceo_dashboard['attrition_rate'] * 100).round(1)
ceo_dashboard = ceo_dashboard.sort_values('avg_salary', ascending=False)

print(ceo_dashboard)

ceo_dashboard.to_csv('../outputs/dept_summary.csv')

             headcount  avg_salary  attrition_rate  avg_performance  \
department
Legal               50   114552.34             6.0             3.52
Engineering        320   113329.71            12.0             3.61
Finance            136   106754.65            10.0             3.68
Marketing          132    93456.17            11.0             3.65
Sales              202    86397.75             8.0             3.62
HR                  76    85623.28            17.0             3.42
Operations          94    85034.55            13.0             3.53

             avg_satisfaction  avg_tenure
department
Legal                    5.28       12.91
Engineering              5.24       14.44
Finance                  5.19       13.47
Marketing                5.23       13.97
Sales                    5.42       13.97
HR                       5.60       15.17
Operations               5.32       14.60

## Part 12 — ML Preparation 🤖

#### 12.1 Target Column

In [63]:
df['target'] = df['status'].isin(['Resigned', 'Terminated']).astype(int)
print(df['target'])

0       0
1       0
2       0
3       0
4       1
       ..
1005    0
1006    0
1007    0
1008    0
1009    0
Name: target, Length: 1010, dtype: int64

#### 12.2 Drop Leaky Columns

In [64]:
# Drop columns that would leak the target or are irrelevant: employee_id, first_name, last_name, email, status, last_promotion_date, hire_date.

df = df.drop(columns=['employee_id', 'first_name', 'last_name', 'full_name', 'email', 'status', 'last_promotion_date', 'hire_date'])
df.head()
print(df.columns)

Index(['gender', 'age', 'city', 'country', 'department', 'job_education',
       'contract_type', 'years_experience', 'salary', 'bonus',
       'performance_rating', 'projects_completed', 'remote_days_per_week',
       'satisfaction_score', 'training_hours', 'certifications', 'is_manager',
       'is_dept_head', 'total_compensation', 'bonus_pct',
       'years_since_promotion', 'tenure_years', 'seniority', 'salary_band',
       'is_remote', 'hire_year', 'hire_month', 'dept_avg_salary',
       'salary_vs_dept_avg', 'salary_rank_in_dept', 'attrited',
       'promotion_speed', 'target'],
      dtype='str')

#### 12.3 One-Hot Encoding

In [65]:
# Encode all remaining categorical columns using pd.get_dummies().


cat_cols = df.select_dtypes(include=['object', 'string']).columns.tolist()
df_dummy = pd.get_dummies(df, columns=cat_cols, drop_first=True)
df_dummy.head(10)

,age,years_experience,salary,bonus,performance_rating,projects_completed,remote_days_per_week,satisfaction_score,training_hours,certifications,...,department_HR,department_Legal,department_Marketing,department_Operations,department_Sales,job_education_High School,job_education_Master,job_education_PhD,contract_type_Full-time,contract_type_Part-time
0,37,16,110200.0,16530.00,5,2,4,5.3,14,1,...,True,False,False,False,False,False,False,True,False,True
1,37,16,98308.0,4915.40,3,6,0,3.0,70,4,...,False,False,False,False,True,False,True,False,True,False
2,51,30,115371.0,5768.55,3,6,0,9.0,36,1,...,False,False,False,True,False,False,True,False,False,False
3,23,2,89000.0,4450.00,3,7,3,6.0,76,2,...,False,False,False,False,False,False,False,False,False,True
4,60,34,123279.0,18491.85,5,3,3,1.0,64,1,...,True,False,False,False,False,False,True,False,False,True
5,26,4,100773.0,10077.30,4,7,2,6.0,76,2,...,False,False,False,False,False,False,True,False,True,False
6,34,13,88982.0,4449.10,3,4,3,10.0,18,1,...,False,False,False,True,False,False,True,False,True,False
7,28,7,84313.0,1686.26,2,2,2,9.0,113,1,...,True,False,False,False,False,False,True,False,False,True
8,59,34,141860.0,21279.00,5,9,4,3.0,19,1,...,False,False,False,False,False,False,True,False,True,False
9,43,5,111835.0,5591.75,3,3,3,5.0,61,6,...,False,False,False,False,False,False,True,False,True,False

#### 12.4 Final NaN Check

In [66]:
# Verify there are zero NaNs remaining. If any exist — handle them.

Nan_count = df.isnull().sum().sum()
print(Nan_count)

0

#### 12.5 X and y Split

In [67]:
# Split into features X (everything except attrition) and target y (attrition column). 
# Print both shapes.


y = df['target']  
X = df.drop(columns=['target']) 
print(f"X.shape: {X.shape}, y.shape: {y.shape}")

X.shape: (1010, 32), y.shape: (1010,)

#### 12.6 Min-Max Normalization

In [68]:
# Normalize all numeric columns in X using the min-max formula — applied to all numeric columns at once.

df_normalized = df.select_dtypes(include=np.number)
df_normalized = (df_normalized - df_normalized.min())/(df_normalized.max() - df_normalized.min())

#### 12.7 Final Check ✅

In [69]:
# Print X.shape, y.value_counts(), and X.dtypes.

print(f"X.shape: {X.shape}")
print(f"y.value_counts():")
print(y.value_counts())
print(f"\ny.dtypes:")
print(y.dtype)
print(f"\nX.dtypes sample:")
print(X.dtypes.head())
print(f"\nX NaN check: {X.isnull().sum().sum()}")

X.shape: (1010, 32)
y.value_counts():
target
0    898
1    112
Name: count, dtype: int64

y.dtypes:
int64

X.dtypes sample:
gender          str
age           int64
city            str
country         str
department      str
dtype: object

X NaN check: 0